### ISSUE TITLE
설정하지 않은 알고리즘이 등장합니다

### ISSUE THREAD

**Issue by bazzi2548** [wzrabbit/boj-totamjung#10]
문제추첨을 통해 퀵슬롯을 생성한뒤 단축키를 이용하여 랜덤문제를 뽑았을때 설정하지 않은 알고리즘이 나오는 경우가 종종있습니다.

**Comment by wzrabbit** [comment]
안녕하세요, 토탐정을 만든 요술토끼입니다!
### 1. 추첨 시 알고리즘을 선택하는 것은, 해당 알고리즘을 포함하는 문제만을 추첨에 포함시켜 주는 기능입니다.
그렇기 때문에, 아쉽게도 특정 알고리즘만 사용하는 문제만 뽑아내는 것은 현재로써는 힘든 상황입니다. 몇 가지 예시를 아래에 적어두겠습니다.
- `AND` 옵션을 선택하고 `수학`, `문자열` 알고리즘을 포함시켜 추첨을 생성한 경우, `수학`, `문자열` 태그를 모두 포함되는 문제만이 매칭됩니다. 예를 들면 매칭된 문제의 알고리즘 분류는 `수학`, `문자열`, `브루트포스 알고리즘` 이 될 수 있습니다.
- `OR` 옵션을 선택하고 `수학`, `문자열` 알고리즘을 포함시켜 추첨을 생성한 경우, `수학`, `문자열` 태그 중 하나 이상의 알고리즘을 포함하는 문제만이 매칭됩니다. 예를 들면 매칭된 문제의 알고리즘 분류는 `수학` 이거나, `문자열`, `구현` 등이 될 수 있습니다.
- 알고리즘 분류가 정확히 `수학`, `문자열` 만이 들어가는 문제를 뽑아내는 것은 현재로써 힘듭니다. 토탐정은 조건에 맞는 문제만을 걸러내기 위해 solved.ac 의 쿼리를 사용하기 때문에, solved.ac 의 쿼리에 없는 검색 기능은 토탐정에서도 사용하실 수 없습니다. 토탐정은 solved.ac 의 쿼리를 편리하게 사용하기 위한 도구라고 생각해 주세요.

### 2. 위의 상황을 이미 알고 계셨음에도 올바르게 작동하지 않는 부분이 있으신가요?
이 경우라면, 제가 쿼리를 확인해 봐야 더 자세한 문제를 알 수 있어 보이는데요, 혹시 말씀하신 문제가 발생했을 당시에 어떤 쿼리를 사용하여 랜덤 추첨을 돌려 보셨는지를 저에게 알려주실 수 있으신가요?
쿼리는 만들어 주신 추첨에서 **수정** 버튼을 누르면 자동으로 생성된 쿼리 전체를 확인하실 수 있습니다.

원하시는 기능을 모두 제공해 드리지 못 해 아쉽습니다. 버그라고 생각하신다면 부디 쿼리와 같은 추가 정보를 알려 주신다면 문제점을 찾아보도록 하겠습니다.

**Comment by bazzi2548** [comment]
알고리즘 설정 탭에서만 원하는 알고리즘을 체크 해놨는데 문제추첨설정탭이랑 연동이 안되는걸까요??
쿼리문은 tier:10..15 solved:500.. solvable:true 입니다.

https://www.acmicpc.net/problem/11664 
위 링크는 랜덤추첨을 이용하여 나온 문제인데 알고리즘 분류에서 단 하나도 나오게 설정하지 않았는데도 불구하고 나온문제입니다.

**Comment by wzrabbit** [comment]
네, **알고리즘 추가** 메뉴와 **문제 추첨** 메뉴에서의 설정은 서로에게 영향을 주지 않습니다.

**알고리즘 추가** 메뉴는 사용자가 알고 있는 알고리즘들을 체크하도록 하게 해, 체크한 알고리즘들을 바탕으로 알고리즘 분류를 공개하기에 앞서 사용자가 알고 있는 알고리즘만으로 문제를 풀 수 있는지를 알려주는 데에 사용됩니다. 문제 추첨에 영향을 주는 요소는 오로지 쿼리 뿐입니다. 그리고 작성하신 쿼리에는 별도의 알고리즘을 추첨에서 제외하는 조건이 포함되어 있지 않습니다.

만약 bazzi님께서 문제 추첨에서 제외하고 싶으신 알고리즘들이 따로 있는 경우에는, 제외하고 싶으신 알고리즘이 적은 경우에는 `NOR` 옵션을 선택하여 추첨을 생성해 주실 수 있고, 많은 경우에는 직접 쿼리에 해당 알고리즘 분류들을 아래 예시와 같이 적어주시면 됩니다.
- 그래프 이론, 브루트포스 알고리즘, 그리디 알고리즘 문제를 제외하고 추첨을 돌리는 쿼리
```
-#graphs -#bruteforcing -#greedy
```

알고리즘 추가 메뉴에서 체크하지 않은 알고리즘이라 하더라도 문제 추첨 메뉴에 영향을 주지 않도록 만든 이유는 아래와 같습니다:
1. 사용자가 모르는 알고리즘이라 하더라도 추첨을 원하는 경우가 생길 수 있기에, 오로지 쿼리만으로 추첨을 결정하도록 구현하였습니다.
2. **사실 이 이유가 제일 큰데, solved.ac API에 보낼 수 있는 쿼리의 글자수는 제한되어 있기에, 사용자가 모르는 알고리즘들을 위의 예시와 같이 전부 넣을 경우 글자수 제한을 넘기게 되어 요청이 불가능해집니다.**

위의 한계로 인해 저도 넣고 싶지만 현재로써는 아직 bazzi님이 기대하신 기능을 넣지는 못 하고 있는 상황입니다, 죄송합니다.
혹시 다른 궁금증이 있다면, 추가로 코멘트 달아 주세요! 감사합니다.
