### ISSUE TITLE
맥OS에서 랜디 단축키가 작동하지 않습니다

### ISSUE THREAD

**Issue by mschadev** [wzrabbit/boj-totamjung#11]
OS 버전: 13.5.2
웨일 브라우저: 3.22.205.18(arm64), 크롬 브라우저: 117.0.5938.62(arm64)
위 브라우저 모두 작동되지 않습니다.

## KeyboardEvent
<img width="909" alt="image" src="https://github.com/wzrabbit/boj-totamjung/assets/29756197/f9786e37-62d5-4f96-aee3-6e8efa9705f3">

**Comment by wzrabbit** [comment]
안녕하세요! 토탐정을 만든 요술토끼입니다.
우선 불편을 드려 죄송합니다. 그리고, 이렇게 콘솔 로그까지 띄워주셔서 감사합니다!

우선 본격적인 문제 해결에 앞서 아래의 상황들을 체크해 주실 수 있을까요?

1. 단축키를 누르는 작업 말고, `토탐정 위젯 우클릭` → `문제 추첨 버튼(주사위 모양 버튼)` 을 눌러 랜디를 돌리는 것은 작동하나요?
2. 시크릿 탭을 켠 상태에서, 토탐정 확장 프로그램만 시크릿 탭에서 사용을 허용했을 때에도 단축키를 이용한 랜디가 잘 작동하지 않나요?
3. 랜디를 돌리기 위해 사용했던 쿼리를 여기에 적어 주시겠어요?

올려주신 로그를 봤을 때 눌린 키가 `¶` 라는 완전 생소한 키여서 `altKey` 의 값과 `code` 의 값을 이용한 새로운 대안을 찾아보려고 합니다.

**Comment by mschadev** [comment]
> 안녕하세요! 토탐정을 만든 요술토끼입니다. 우선 불편을 드려 죄송합니다. 그리고, 이렇게 콘솔 로그까지 띄워주셔서 감사합니다!
> 
> 우선 본격적인 문제 해결에 앞서 아래의 상황들을 체크해 주실 수 있을까요?
> 
> 1. 단축키를 누르는 작업 말고, `토탐정 위젯 우클릭` → `문제 추첨 버튼(주사위 모양 버튼)` 을 눌러 랜디를 돌리는 것은 작동하나요?
> 2. 시크릿 탭을 켠 상태에서, 토탐정 확장 프로그램만 시크릿 탭에서 사용을 허용했을 때에도 단축키를 이용한 랜디가 잘 작동하지 않나요?
> 3. 랜디를 돌리기 위해 사용했던 쿼리를 여기에 적어 주시겠어요?
> 
> 올려주신 로그를 봤을 때 눌린 키가 `¶` 라는 완전 생소한 키여서 `altKey` 의 값과 `code` 의 값을 이용한 새로운 대안을 찾아보려고 합니다.

1. 작동합니다.
2. 크롬, 웨일 모두  시크릿 탭에서 작동하지 않습니다.
3. `tier:1..15 solvable:true (tag:trie|tag:string|tag:parsing)`

추가로 몇가지 살펴봤는데, 해당 키는 맥에서 `Alt` + `다른키` 했을 때 나오는 문자였습니다.
예를 들면 1번부터 9번까지 `¡` `™` `£` `¢` `∞` `§` `¶` `•` `ª` 입니다.

입력 소스에 문제가 있는 것 같아 입력기에서 설정을 바꿔봐도 브라우저에서 인식하는 문자는 동일하게 나왔습니다.

몇번 삽질을 더 해봤는데 `Alt + Control+ 숫자키`로 입력해야 랜디가 정상적으로 동작합니다.
토탐정 랜디 설정에서 맥OS일경우 단축키 설명을 `Options + Control 숫자키`로 변경해주시는게 좋을 것 같습니다.

**Comment by wzrabbit** [comment]
자세한 정보 알려주셔서 정말 감사합니다.
화요일~수요일 사이로 문제 해결해 볼 예정입니다.

**Comment by wzrabbit** [comment]
안녕하세요! 보다 완화된 조건으로 눌린 단축키가 숫자인지를 확인하도록 방식을 조금 바꾸어 보았습니다. 여건이 되신다면 아래의 파일을 다운로드 하신 후, 테스트 해 보실 수 있을까요?

[totamjung_Plorence.zip](https://github.com/wzrabbit/boj-totamjung/files/12728682/totamjung_Plorence.zip)

수동 설치 방법은 [이 페이지](https://github.com/wzrabbit/boj-totamjung#%EC%88%98%EB%8F%99-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)를 참고하시면 됩니다.
기존에 설치되어 있던 토탐정을 삭제하실 필요는 없습니다. 다만 잠시 비활성화를 해 주시면, 데이터를 잃지 않고도 테스트를 하실 수 있습니다.

다른 문제가 있다면 언제든지 말씀해 주세요!

**Comment by mschadev** [comment]
> 안녕하세요! 보다 완화된 조건으로 눌린 단축키가 숫자인지를 확인하도록 방식을 조금 바꾸어 보았습니다. 여건이 되신다면 아래의 파일을 다운로드 하신 후, 테스트 해 보실 수 있을까요?
> 
> [totamjung_Plorence.zip](https://github.com/wzrabbit/boj-totamjung/files/12728682/totamjung_Plorence.zip)
> 
> 수동 설치 방법은 [이 페이지](https://github.com/wzrabbit/boj-totamjung#%EC%88%98%EB%8F%99-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)를 참고하시면 됩니다. 기존에 설치되어 있던 토탐정을 삭제하실 필요는 없습니다. 다만 잠시 비활성화를 해 주시면, 데이터를 잃지 않고도 테스트를 하실 수 있습니다.
> 
> 다른 문제가 있다면 언제든지 말씀해 주세요!


https://github.com/wzrabbit/boj-totamjung/assets/29756197/e82f95ac-de53-4c03-8587-d59632dae47a

크롬, 웨일 브라우저 모두 작동됩니다. 고생하셨습니다!

**Comment by wzrabbit** [comment]
작동한다니 정말 다행이군요!
변경사항은 곧 다음 버전으로 배포할 예정입니다.

다만 스토어에 반영되기까지는 시간이 다소 걸릴 수 있음을 양해해 주시면 감사하겠습니다, 보통 1~3일 정도 걸립니다.

도와주셔서 정말 감사합니다! 스토어에 성공적으로 반영된 것이 확인되면 이 이슈는 닫겠습니다.

<img src="https://user-images.githubusercontent.com/87642422/233928933-505b06b9-5460-4d73-bf1b-4addd84c9e9a.png" width="35px" />
