### ISSUE TITLE
GUIDE.md 페이지의 링크 오류

### ISSUE THREAD

**Issue by ShyRoute** [wzrabbit/boj-totamjung#15]
GUIDE.md 첫번째 줄의 README 링크 주소로 접근하면 404 - page not found 에러가 발생합니다.

> 이 페이지는 토탐정의 기본적인 사용법을 설명합니다. 설치 방법은 [README](https://github.com/wzrabbit/boj-totamjung/edit/experimental/README.md) 페이지를 참고해 주세요.

이를 현재 README의 주소인 https://github.com/wzrabbit/boj-totamjung/blob/main/README.md 로 수정하면 좋을 것 같습니다.

토탐정 신규 설치 시 나오는 페이지인 만큼, 중요한 오류라고 생각하여 건의하게 되었습니다.

**Comment by wzrabbit** [comment]
안녕하세요! 토탐정을 관리하고 있는 요술토끼입니다. 우선, 불편을 드려 죄송합니다.

확인 결과 정말로 잘못된 링크를 안내하고 있었네요! 지금은 올바르게 안내할 수 있도록 말씀해 주신 주소인 https://github.com/wzrabbit/boj-totamjung/blob/main/README.md 로 변경했습니다.

말씀해 주신대로 안내 페이지는 유저분들께 중요한 페이지인만큼, 가능한 한 상세하게 설명하고자 노력하고 있으니 혹시 미흡하다고 생각되거나, 개선되면 좋을 만한 점이 있다면 언제든지 알려 주세요!

내일부터 설날이네요, 소중한 분들과 재밌는 시간 보내셨으면 좋겠습니다.
제보해 주셔서 감사합니다!

**Comment by ShyRoute** [comment]
확인해 주셔서 감사합니다. 즐거운 연휴 되세요 :)
