### ISSUE TITLE
테마 적용 시 CodeMirror 에디터 가시성 문제

### ISSUE THREAD

**Issue by copyrat90** [wzrabbit/boj-totamjung#2]
토탐정 테마를 켜면 CodeMirror 에디터 사용에 불편한 점이 있습니다.

# "블로그 글 쓰기" , 문제 하단 "메모 작성하기" 공통

## 커서가 검정색이라서 잘 보이지 않는 문제
스크린샷에서는 `타`와 `고` 사이에 커서가 있습니다.
![image](https://user-images.githubusercontent.com/34793045/166094387-b56f0e87-7eeb-441e-88c6-fb0414aee8cd.png)

## 블록 지정하면 글자가 보이지 않는 문제
![image](https://user-images.githubusercontent.com/34793045/166094399-c7462fe5-4060-4b55-abb5-4fd9efe009a8.png)

# "블로그 글 쓰기"

## 태그는 화이트 테마 그대로인 문제
![image](https://user-images.githubusercontent.com/34793045/166094654-10c7019d-f79e-4c50-a6ac-49d7b3d9d71c.png)

구글 폼에는 스크린샷 첨부가 안 돼서 이슈로 올렸습니다.

**Comment by wzrabbit** [comment]
안녕하세요, 토탐정 제작자 요술토끼입니다.
해당 문제를 확인하였으며, 정식 출시 때 다른 오류들과 같이 수정하도록 하겠습니다.
특히 블로그 등의 글쓰기 창과 이번에 새로 생긴 그룹 시스템의 글쓰기 창들을 고치도록 하겠습니다.
제보해 주셔서 감사합니다.
