### ISSUE TITLE
태그 이름이 바뀌었을때 아는 태그더라도 모르는 태그로 나오는 현상

### ISSUE THREAD

**Issue by LimePencil** [wzrabbit/boj-totamjung#3]
![image](https://user-images.githubusercontent.com/71117066/171001276-29d5c79a-2476-4d2e-8e84-ddd78067c2c8.png)

다익스트라와 플로이드-워샬이 이름이 데이크스트라와 플로이드-워셜로 바뀌면서 모른다고 나와 있는데 업데이트가 필요한것 같습니다.

**Comment by wzrabbit** [comment]
안녕하세요, 토탐정 제작자 요술토끼입니다.
해당 문제를 확인하였으며, 해당 버전을 배포했습니다.
다만 스토어에 반영되기까지는 1~2일 정도의 시간이 걸릴 수 있으니, 이 점은 양해 부탁드리겠습니다.
Github Releases에는 새로운 버전을 등록했습니다.
제보해 주셔서 감사합니다.
