### ISSUE TITLE
[BUG] 테마 적용시, 표가 제대로 안보이는 문제

### ISSUE THREAD

**Issue by Bing-su** [wzrabbit/boj-totamjung#4]
[21609번: 상어 중학교](https://www.acmicpc.net/problem/21609)

## 테마 미적용
![Cap 2022-07-13 13-43-27-885](https://user-images.githubusercontent.com/37621276/178652349-c291ef4b-a51b-4c3c-a9a1-b2bbcf26d8af.png)

## 테마 적용
![Cap 2022-07-13 13-43-33-252](https://user-images.githubusercontent.com/37621276/178652361-13a56761-9522-4fe2-b67a-9f40b10aed94.jpg)

------

[21608번: 상어 초등학교](https://www.acmicpc.net/problem/21608)

## 테마 미적용
![Cap 2022-07-13 13-51-36-663](https://user-images.githubusercontent.com/37621276/178653318-3e0c6ee8-3897-4435-9a23-bf7f6e846226.png)

## 테마 적용
![Cap 2022-07-13 13-51-39-462](https://user-images.githubusercontent.com/37621276/178653346-b9961276-8ba6-45ca-9719-4d7ea2e8682a.jpg)

위 상어 중학교 문제만큼 심각하진 않지만, 빈칸 구분이 잘 안됩니다.

**Comment by wzrabbit** [comment]
![preview](https://user-images.githubusercontent.com/87642422/178747677-861070f7-8517-4583-ad47-701229ee5d06.png)

안녕하세요, 토탐정 제작자 요술토끼입니다.
해당 문제를 확인하였으며, 위의 스크린샷처럼 표의 디자인을 약간 개선해보았습니다.
해당 문제에서 붉은색 칸이 보이지 않는 현상을 해결하였고, 빈칸이 구분되도록 표 전체에 희미하게 윤곽선을 넣었습니다.

여전히 디자인이 마음에 안 드신다면, 아래에 추가로 의견을 적어주시면 감사하겠습니다!
변경 사항은 새로운 버전으로 올렸습니다. 다만 반영되기까지는 1~3일 정도의 시간이 걸릴 수 있음을 양해해 주셨으면 합니다.
제보해 주셔서 감사합니다.

**Comment by Bing-su** [comment]
![LGTM](https://user-images.githubusercontent.com/37621276/178859496-645122ad-4f76-4af7-94f2-a6e1ab3c9721.png)

**Comment by genuio-kyle** [comment]
[2468](https://www.acmicpc.net/problem/2468) 번은 회색인데 적용이 안되네요 ㅜㅜ
![image](https://user-images.githubusercontent.com/97570464/212799016-d709976c-b4fa-455e-93d9-915c69c0b586.png)
![image](https://user-images.githubusercontent.com/97570464/212799032-7f4f7e0a-e3e2-439c-8eb7-5ea941eb2441.png)

**Comment by wzrabbit** [comment]
![ttj_resolve](https://user-images.githubusercontent.com/87642422/213172446-f16988d4-e08c-493f-befb-058f82066093.PNG)

안녕하세요, @genuio-kyle 님.
2468번, 2499번, 18823번에 대해 작업을 완료했습니다. 스토어에 새로운 버전의 프로그램을 제출했으니, 며칠 내로 반영될 거에요.
문제마다 표의 색칠된 부분의 클래스/속성이 제각각이라, 이러한 문제를 발견하는 족족 수동으로 작업해서 업데이트하려 합니다.
제보해 주셔서 감사합니다. 명절 잘 보내세요!
