### ISSUE TITLE
문제 추첨 - 이름/쿼리 빠른 수정 기능 제안

### ISSUE THREAD

**Issue by iamgamja** [wzrabbit/boj-totamjung#5]
문제 추첨 이름/쿼리를 수정할 수 있으면 좋을 것 같아요

![Screenshot_20221018-122309_Kiwi Browser](https://user-images.githubusercontent.com/68046824/196328623-ea309ce4-8451-46e7-91ac-bb7e405c76fc.jpg)
이런 식으로 수정 버튼을 만들고, 누르면 
![SmartSelect_20221018-123058_Kiwi Browser](https://user-images.githubusercontent.com/68046824/196329164-aeb23026-3beb-4a14-a611-1e1f296f52c2.jpg)
이렇게 수정할 수 있게 하면 어떨까요?

**Comment by wzrabbit** [comment]
안녕하세요, 토탐정을 만든 요술토끼입니다.
이미 만들어진 추첨을 스크린샷처럼 클릭하여 수정할 수 있는 기능을 요청하셨네요. 좋은 아이디어입니다.
수정 기능은 며칠 내로 구현해 보도록 하겠습니다. 다만 쿼리의 경우 최대 300자까지 들어갈 수 있기 때문에 수정 기능을 구현하게 된다면 따로 팝업 창으로 띄우지 않을까 하는 생각이 드네요.
건의해 주셔서 감사합니다.

**Comment by wzrabbit** [comment]
![ttj-popup](https://user-images.githubusercontent.com/87642422/201345231-d59ca9e4-863d-4dab-9b1a-7b4c8585d6cf.PNG)

안녕하세요, 반영이 늦어 정말 죄송합니다.
건의해 주신 『이미 만들어진 추첨의 제목, 쿼리를 수정할 수 있는 기능』 은 위의 스크린샷과 같이,
팝업 형태로 반영하였습니다.

스토어에 제출 후, 승인이 되면 반영될 것입니다.
