### ISSUE TITLE
설정 내보내기, 불러오기 기능 요청

### ISSUE THREAD

**Issue by endixk** [wzrabbit/boj-totamjung#9]
설정한 옵션 및 추첨 쿼리가 초기화되는 일이 간혹 있는데, 매번 재설정하기가 너무 번거롭습니다 ㅠㅠ

알고리즘 설정, 문제 추첨 설정을 텍스트 파일로 내보내고, 내보낸 텍스트 파일을 읽어들여 설정을 복구할 수 있는 기능이 추가된다면 매우 유용할 것 같습니다!

**Comment by wzrabbit** [comment]
안녕하세요, 토탐정을 만든 요술토끼입니다.
이슈를 오래전에 작성해 주셨음에도 기능들을 반영 못 해서 정말 죄송합니다. 팀플을 병행하고 있어 토탐정의 관리를 제대로 못 하고 있네요.

되는대로 토탐정 내에서 별도의 세이브파일을 내보내고, 불러오는 기능을 구현해 배포해 보도록 하겠습니다.
다시 한 번 죄송합니다.

**Comment by wzrabbit** [comment]
안녕하세요, 설정을 내보내고 불러오는 등 설정 데이터를 관리할 수 있는 기능을 모두 구현했습니다.
해당 기능은 추후 나올 다음 버전인 `v1.2`에 배포할 계획입니다!

미리 `v1.2` 기준의 가이드 페이지의 **설정 데이터 관리하기** 문단을 공유해드리겠습니다. 감사합니다!
- https://github.com/wzrabbit/boj-totamjung/wiki/%ED%86%A0%ED%83%90%EC%A0%95-%EC%82%AC%EC%9A%A9-%EA%B0%80%EC%9D%B4%EB%93%9C#%EC%84%A4%EC%A0%95-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

이슈는 `v1.2` 가 배포되면 닫을 계획입니다.
